# Site settings
title: "Dean Barnett Resume"
description: "Experience and Skills"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Dean Barnett"
resume_title:                   "Senior Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "work@deano.io"

resume_header_contact_info:     "work@deano.io"
display_header_contact_info:    "true"

resume_header_intro: "<p>Senior Engineer with 10 years industry experience at startups building Rails, Flask and Go applications, with a focus on application stability and solid Engineering practices.</p>"

# resume_looking_for_work:        "yes"

# Decide which sections to use
resume_section_experience:      true
resume_section_projects:        true
resume_section_skills:          true

# Resume social links
resume_social_links:
  resume_github_url:            "https://github.com/deanobarnett"
  resume_gitlab_url:            "https://gitlab.com/deanobarnett"
  resume_website_url:           "https://cv.deano.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
